# Generated by Django 3.0 on 2020-10-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingresar solo los nombres', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Ingresar solo los apellidos', max_length=50, verbose_name='Apellidos')),
                ('apellido_casada', models.CharField(blank=True, help_text='Ingresar solo los apellidos', max_length=50, null=True, verbose_name='Apellido de Casada')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(help_text='Ejemplo: 01/01/1991', verbose_name='Fecha de nacimiento')),
                ('funcion', models.CharField(choices=[('A', 'Auxiliar de Enfermeria'), ('J', 'Enfermera Jefe de Servicio'), ('S', 'Supervisor de Enfermeria')], default='A', max_length=1, verbose_name='Función')),
                ('renglon', models.CharField(choices=[('1', 'Renglón 011'), ('2', 'Renglón 182')], default='1', max_length=1, verbose_name='Renglón')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Servicio', verbose_name='Servicio asignado')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
            },
        ),
    ]
