# Generated by Django 3.0 on 2020-10-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientosCentral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha que se recolectaron los tratamientos', verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], default='F', max_length=1, verbose_name='Turno')),
                ('admon_oxi', models.PositiveIntegerField(default=0, verbose_name='Administraciones de oxígeno')),
                ('arreglos', models.PositiveIntegerField(default=0, verbose_name='Arreglo de unidades')),
                ('canalizaciones', models.PositiveIntegerField(default=0, verbose_name='Canalizaciones')),
                ('curaciones', models.PositiveIntegerField(default=0, verbose_name='Curaciones')),
                ('hipodermia', models.PositiveIntegerField(default=0, verbose_name='Hipodermias')),
                ('limpieza_unidad', models.PositiveIntegerField(default=0, verbose_name='Limpieza de unidades')),
                ('traslados_ekg', models.PositiveIntegerField(default=0, verbose_name='Traslados de pacientes a electrocardiograma')),
                ('traslados_rx', models.PositiveIntegerField(default=0, verbose_name='Traslados de pacientes a rayos X')),
                ('nebulizaciones', models.PositiveIntegerField(default=0, verbose_name='Nebulizaciones')),
                ('peq_cirugias', models.PositiveIntegerField(default=0, verbose_name='Pequeñas cirugias')),
                ('recolect_muestras', models.PositiveIntegerField(default=0, verbose_name='Recolecciones de muestras')),
                ('transfusiones', models.PositiveIntegerField(default=0, verbose_name='Transfusiones')),
                ('encargado', models.CharField(blank=True, max_length=250, verbose_name='Encargado')),
                ('servicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Tratamientos de Central de equipos',
                'verbose_name_plural': 'Tratamientos de Central de equipos',
                'db_table': 'tratamiento_central',
            },
        ),
    ]
